# ************************************************** #
# ***************** Subscriptions ****************** #
# ************************************************** #

type Subscription {
  updateBooking: String
}
