# ************************************************** #
# ******************* Gallery ********************** #
# ************************************************** #

type Query {
  gallery(galleryId: Int!): Gallery!
}
