# ************************************************** #
# **************** Operating times ***************** #
# ************************************************** #

type Query {
  operatingTimes: [OperatingTime!]!
}
