# ************************************************** #
# ******************* Providers ******************** #
# ************************************************** #

type Query {
  providers(search: String): [Provider!]!
}
