# ************************************************** #
# ******************* provider ********************* #
# ************************************************** #

type Query {
  provider: Provider
}
