# ************************************************** #
# ******************* Provider ********************* #
# ************************************************** #

type Query {
  provider: Provider
}
