# ************************************************** #
# ******************* Providers ******************** #
# ************************************************** #

type Query {
  providers: [Provider!]!
}
