# ************************************************** #
# ******************* providers ******************** #
# ************************************************** #

type Query {
  providers: [Provider!]!
}
