# ************************************************** #
# ******************* services ********************* #
# ************************************************** #

type Query {
  services: [Service!]!
}
