# ************************************************** #
# ******************* Socials ********************** #
# ************************************************** #

type Query {
  socials: [Social!]!
}
