# ************************************************** #
# ******************** Staff *********************** #
# ************************************************** #

type Query {
  staff(staffId: Int!): Staff!
}
