# ************************************************** #
# ******************* Service ********************** #
# ************************************************** #

type Query {
  service(serviceId: Int!): Service!
}
