# ************************************************** #
# ******************* Comment ********************** #
# ************************************************** #

type Query {
  comment(commentId: Int!): Comment!
}
