# ************************************************** #
# **************** Operating time ****************** #
# ************************************************** #

type Query {
  operatingTime(operatingTimeId: Int!): OperatingTime!
}
