# ************************************************** #
# **************** Operating times ***************** #
# ************************************************** #

type Query {
  operatingTimes(
    limit: Int
    cursor: Int
    page: Int
    paginationType: PaginationType
  ): OperatingTimesQueryResults
}
