# ************************************************** #
# ******************* Provider ********************* #
# ************************************************** #

type Query {
  provider(providerId: Int): Provider
}
